
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kashmira Lokhande
 */
public class CreateUCP extends javax.swing.JFrame {

    /**
     * Creates new form CreateUCP
     */
    public CreateUCP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UCPName = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter the name of UCP");

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(create)
                        .addGap(18, 18, 18)
                        .addComponent(cancel))
                    .addComponent(UCPName))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(UCPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(cancel))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
         if(metricsuite.checkproject()){
            JOptionPane.showMessageDialog(null, "No project created");
        }
        else{
             int count= metricsuite.jTabbedPane1.getTabCount();
             ImageIcon close_icon = new ImageIcon(new ImageIcon( this.getClass().getResource("closeTab.png")).getImage().getScaledInstance(15, 15, Image.SCALE_DEFAULT));
        
//             metricsuite.jTabbedPane1.addTab(UCPName.getText() , new NewUCPdata().getContentPane());
            
            metricsuite.jTabbedPane1.addTab(UCPName.getText(), close_icon, new NewUCPdata().getContentPane(),"UCP");
             if(UCPName.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null, "Please enter UCP name");
            }
            else{
                String UcpName = UCPName.getText().trim();
                double TCF = 0.0;
                double ECF = 0.0;
                int simpleUC = 0;
                int averageUC = 0;
                int complexUC = 0;
                int UUCWsimple = 0;
                int UUCWaverage = 0;
                int UUCWcomplex = 0;
                int UUCW = 0;
                int simpleActor = 0;
                int averageActor = 0;
                int complexActor = 0;
                int UAWsimple = 0;
                int UAWaverage = 0;
                int UAWcomplex = 0;
                int UAW = 0;
                int UUCP = 0;
                int PF = 0;
                double UCP = 0.0;
                int LOCperpm = 0;
                int LOCperUCP = 0;
                int estimatedHrs = 0;
                int estimatedLOC = 0;
                int estimatedPM = 0;
                boolean tabOpen = true;
                UCPdata ucp = new UCPdata(UcpName, TCF, ECF, simpleUC, averageUC, complexUC, UUCWsimple, UUCWaverage, UUCWcomplex, UUCW, simpleActor, averageActor, complexActor, UAWsimple, UAWaverage, UAWcomplex, UAW, UUCP, PF, UCP, LOCperpm, LOCperUCP, estimatedHrs, estimatedLOC, estimatedPM, tabOpen);
                metricsuite.saveUCPtofile(ucp);
                metricsuite.AddUCPtoTree(UcpName);
             }
             
         }
         dispose();
         
    }//GEN-LAST:event_createActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UCPName;
    private javax.swing.JButton cancel;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
