
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kashmira Lokhande
 */
public class NewUCPdata extends javax.swing.JFrame {
    public static  ArrayList<projectData> project;
    public static  ArrayList<UCPdata> ucp;
    public static  String projname;
    public static double tcfvalue;
    public static double ecfvalue;
    public static int simpleUCvalue;
    public static int averageUCvalue;
    public static int complexUCvalue;
    public static int UUCWvalue;
    public static int simpleActorvalue;
    public static int averageActorvalue;
    public static int complexActorvalue;
    public static int UAWvalue;
    public static int UUCPvalue;
    public static int PFvalue;
    public static int LOCperPMvalue;
    public static int LOCperUCPvalue;
    public static double UCPvalue;
    public static int estimatedHour;
    public static int estimatedLOC;
    public static int estimatedPM;
    
    
    /**
     * Creates new form NewUCPdata
     */
    public NewUCPdata() {
        initComponents();
        project = new ArrayList<projectData>();
        ucp = new  ArrayList<UCPdata>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void fetchprojdetails(){
        try{
            project.clear();
            System.out.println("Inside fetchprojdetails "+projname);
            FileInputStream file = new FileInputStream(projname+".ms");
            ObjectInputStream inputFile = new ObjectInputStream(file);
            boolean endofFile = false;
            while(!endofFile){
                   try{
                        project.add((projectData) inputFile.readObject());
                   }
                   catch(EOFException e){
                       endofFile = true;
                   }
                   catch(Exception f){
                        JOptionPane.showMessageDialog(null, f.getMessage());
                   }
            }
            inputFile.close();
            
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(Exception k){
                        JOptionPane.showMessageDialog(null, k.getMessage());
                   }

    }
            public static void fetchUCPdetails(){
        try{
            ucp.clear();
            System.out.println("Inside fetchUCPdetails" + project.get(0).getUCPDataFile());
            FileInputStream file13 = new FileInputStream(project.get(0).getUCPDataFile());
            ObjectInputStream inputFile13 = new ObjectInputStream(file13);
            boolean endofFile = false;
            while(!endofFile){
                   try{
                        ucp.add((UCPdata) inputFile13.readObject());
                   }
                   catch(EOFException e){
                       endofFile = true;
                   }
                   catch(Exception f){
                       // JOptionPane.showMessageDialog(null, f.getMessage());
                   }
            }
            inputFile13.close();
        }
        catch(IOException e){     
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(Exception k){
//                        JOptionPane.showMessageDialog(null, k.getMessage());
                   }
        
    }
    public static void setTCF(double tcf){
        System.out.println(tcf);
        double TCFRounded = Math.round(tcf * 100D) / 100D;
        TCFvalue.setText(Double.toString(TCFRounded));
    }
    public static void setECF(double ecf){
        System.out.println("ECF is "+ ecf);
        double ECFRounded = Math.round(ecf * 100D) / 100D;
        ECFvalue.setText(Double.toString(ECFRounded));
    }
    public static void saveCurrentUCP(String name){
        try{
            fetchprojdetails();
            fetchUCPdetails();
        double TCFval = Double.parseDouble(TCFvalue.getText());
        double ECFval = Double.parseDouble(ECFvalue.getText());
        int SimpleUCval = Integer.parseInt(SimpleUC.getText());
        int AverageUCval = Integer.parseInt(AverageUC.getText());
        int ComplexUCval = Integer.parseInt(ComplexUC.getText());
        int UUCWSimpleval = Integer.parseInt(UUCWSimple.getText());
        int UUCWAverageval = Integer.parseInt(UUCWAverage.getText());
        int UUCWComplexval = Integer.parseInt(UUCWComplex.getText());
        int UUCWval = Integer.parseInt(UUCW.getText());
        int SimpleActorval = Integer.parseInt(SimpleActor.getText());
        int AverageActorval = Integer.parseInt(AverageActor.getText());
        int ComplexActorval = Integer.parseInt(ComplexActor.getText());
        int UAWSimpleval = Integer.parseInt(UAWSimple.getText());
        int UAWAverageval = Integer.parseInt(UAWAverage.getText());
        int UAWComplexval = Integer.parseInt(UAWComplex.getText());
        int UAWval = Integer.parseInt(UAW.getText());
        int UUCPval = Integer.parseInt(UUCP.getText());
        int PFval = Integer.parseInt(PF.getText());
        int LOCperPMval = Integer.parseInt(LOCperPM.getText());
        int LOCperUCPval = Integer.parseInt(LOCperUCP.getText());
        double UCPval = Double.parseDouble(UCP.getText());
        int Estimatedhoursval;
        int EstimatedLOCval;
        int EstimatedPMval;
        
        if(hours.getText() == ""){
            Estimatedhoursval = 0;
        }
        else{
            Estimatedhoursval = Integer.parseInt(hours.getText());
        }
        if(LOC.getText() == ""){
            EstimatedLOCval = 0;
        }
        else{
            EstimatedLOCval = Integer.parseInt(LOC.getText());
        }
        if(PM.getText() == ""){
            EstimatedPMval = 0;
        }
        else{
            EstimatedPMval = Integer.parseInt(PM.getText());
        }
        //FPdata fd = new FPdata(FPname, EI, EO, EInq, ILF, EIF, EIWeight, EOWeight, EInqWeight, ILFWeight, EIFWeight, EIvalue, EOvalue, EInqvalue, ILFvalue, EIFvalue, total, VAFvalue, language, FPcal, codeSize);
        for (int i =0 ; i<ucp.size(); i++){
            
            if(ucp.get(i).getUCPName().equals(name)){
                ucp.get(i).setTCF(TCFval);
                ucp.get(i).setECF(ECFval);
                ucp.get(i).setSimpleUC(SimpleUCval);
                ucp.get(i).setAverageUC(AverageUCval);
                ucp.get(i).setComplexUC(ComplexUCval);
                ucp.get(i).setUUCWsimple(UUCWSimpleval);
                ucp.get(i).setUUCWaverage(UUCWAverageval);
                ucp.get(i).setUUCWcomplex(UUCWComplexval);
                ucp.get(i).setUUCW(UUCWval);
                ucp.get(i).setSimpleActor(SimpleActorval);
                ucp.get(i).setAverageActor(AverageActorval);
                ucp.get(i).setComplexActor(ComplexActorval);
                ucp.get(i).setUAWsimple(UAWSimpleval);
                ucp.get(i).setUAWaverage(UAWAverageval);
                ucp.get(i).setUAWcomplex(UAWComplexval);
                ucp.get(i).setUAW(UAWval);
                ucp.get(i).setUUCP(UUCPval);
                ucp.get(i).setPF(PFval);
                ucp.get(i).setLOCperpm(LOCperPMval);
                ucp.get(i).setLOCperUCP(LOCperUCPval);
                ucp.get(i).setPF(PFval);
                ucp.get(i).setUCP(UCPval);
                ucp.get(i).setEstimatedHrs(Estimatedhoursval);
                ucp.get(i).setEstimatedLOC(EstimatedLOCval);
                ucp.get(i).setEstimatedPM(EstimatedPMval);
                ucp.get(i).setTabOpen(true);
            }
        }
        
            FileOutputStream file = new FileOutputStream(project.get(0).getUCPDataFile());
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            for (int j =0 ; j<ucp.size(); j++){
                outputFile.writeObject(ucp.get(j));
            }
            
            outputFile.close();
            
        }
                catch(IOException e){
            System.out.println("sdfsf"+e.getMessage());            
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(Exception k){
            System.out.println("jkjkj"+k.getMessage());
//                        JOptionPane.showMessageDialog(null, k.getMessage());
                   }
        
    }
    public static void setUCPValuesOnOpen(UCPdata ucpd){
        TCFvalue.setText(Double.toString(ucpd.getTCF()));
        ECFvalue.setText(Double.toString(ucpd.getECF()));
        SimpleUC.setText(Integer.toString(ucpd.getSimpleUC()));
        AverageUC.setText(Integer.toString(ucpd.getAverageUC()));
        ComplexUC.setText(Integer.toString(ucpd.getComplexUC()));
        UUCWSimple.setText(Integer.toString(ucpd.getUUCWsimple()));
        UUCWAverage.setText(Integer.toString(ucpd.getUUCWaverage()));
        UUCWComplex.setText(Integer.toString(ucpd.getUUCWcomplex()));
        UUCW.setText(Integer.toString(ucpd.getUUCW()));
        SimpleActor.setText(Integer.toString(ucpd.getSimpleActor()));
        AverageActor.setText(Integer.toString(ucpd.getAverageActor()));
        ComplexActor.setText(Integer.toString(ucpd.getComplexActor()));
        UAWSimple.setText(Integer.toString(ucpd.getUUCWsimple()));
        UAWAverage.setText(Integer.toString(ucpd.getUAWaverage()));
        UAWComplex.setText(Integer.toString(ucpd.getUAWcomplex()));
        UAW.setText(Integer.toString(ucpd.getUAW()));
        UUCP.setText(Integer.toString(ucpd.getUUCP()));
        PF.setText(Integer.toString(ucpd.getPF()));
        LOCperPM.setText(Integer.toString(ucpd.getLOCperpm()));
        LOCperUCP.setText(Integer.toString(ucpd.getLOCperUCP()));
        UCP.setText(Double.toString(ucpd.getUCP()));
        hours.setText(Integer.toString(ucpd.getEstimatedHrs()));
        PM.setText(Integer.toString(ucpd.getEstimatedPM()));
        LOC.setText(Integer.toString(ucpd.getEstimatedLOC()));
    }
    
    public static void tabClosed(String UCPname){
         try{
            fetchprojdetails();
            fetchUCPdetails();
            for (int i =0 ; i<ucp.size(); i++){
            
            if(ucp.get(i).getUCPName().equals(UCPname)){
                ucp.get(i).setTabOpen(false);
            }
            }
             FileOutputStream file = new FileOutputStream(project.get(0).getUCPDataFile());
            ObjectOutputStream outputFile = new ObjectOutputStream(file);
            for (int j =0 ; j<ucp.size(); j++){
                outputFile.writeObject(ucp.get(j));
            }
            
            outputFile.close();
            
        }
                catch(IOException e){
            System.out.println("sdfsf"+e.getMessage());            
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }
        catch(Exception k){
            System.out.println("jkjkj"+k.getMessage());
//                        JOptionPane.showMessageDialog(null, k.getMessage());
                   }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        LOCperPM = new javax.swing.JTextField();
        ECFvalue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UCP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hours = new javax.swing.JTextField();
        LOC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SimpleUC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SimpleActor = new javax.swing.JTextField();
        AverageUC = new javax.swing.JTextField();
        AverageActor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ComplexActor = new javax.swing.JTextField();
        PM = new javax.swing.JTextField();
        UAWSimple = new javax.swing.JTextField();
        UAWAverage = new javax.swing.JTextField();
        UAWComplex = new javax.swing.JTextField();
        UAW = new javax.swing.JTextField();
        ComplexUC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        UUCWSimple = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        UUCWAverage = new javax.swing.JTextField();
        UUCWComplex = new javax.swing.JTextField();
        UUCW = new javax.swing.JTextField();
        PF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TCFButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        TCFvalue = new javax.swing.JTextField();
        LOCperUCP = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        UUCP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(650, 488));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ECF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("LOC/UCP");

        LOCperPM.setText("700");

        ECFvalue.setEditable(false);

        jLabel2.setText("Simple");

        jLabel3.setText("Average");

        jLabel4.setText("Complex");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Weight");

        UCP.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Number of Use Cases");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Compute UCP");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Result");

        jLabel8.setText("5");

        hours.setEditable(false);

        LOC.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Weight");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Number of Actors");

        jLabel9.setText("10");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Result");

        jLabel10.setText("15");

        jLabel13.setText("Simple");

        jLabel18.setText("3");

        jLabel14.setText("1");

        jLabel15.setText("Average");

        PM.setEditable(false);

        UAWSimple.setEditable(false);

        UAWAverage.setEditable(false);

        UAWComplex.setEditable(false);

        UAW.setEditable(false);

        jLabel16.setText("2");

        UUCWSimple.setEditable(false);

        jLabel17.setText("Complex");

        UUCWAverage.setEditable(false);

        UUCWComplex.setEditable(false);

        UUCW.setEditable(false);

        PF.setText("20");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("PF");

        TCFButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TCFButton.setText("TCF");
        TCFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCFButtonActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("LOC/PM");

        TCFvalue.setEditable(false);
        TCFvalue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TCFvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCFvalueActionPerformed(evt);
            }
        });

        LOCperUCP.setText("100");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("UUCW");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("UAW");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Estimate Hours");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Estimate LOC");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Estimate PM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("UUCP");

        UUCP.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(TCFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317)
                        .addComponent(TCFvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317)
                        .addComponent(ECFvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(SimpleUC, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(UUCWSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(54, 54, 54)
                        .addComponent(AverageUC, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(UUCWAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel13)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel14)
                        .addGap(64, 64, 64)
                        .addComponent(SimpleActor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(UAWSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel15)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel16)
                        .addGap(64, 64, 64)
                        .addComponent(AverageActor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(UAWAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel17)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel18)
                        .addGap(64, 64, 64)
                        .addComponent(ComplexActor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UAW, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UAWComplex, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(307, 307, 307)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LOC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PM, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LOCperPM, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(181, 181, 181)
                                            .addComponent(PF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(181, 181, 181)
                                            .addComponent(LOCperUCP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UCP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel10)
                                .addGap(54, 54, 54)
                                .addComponent(ComplexUC, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel23))))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UUCW, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(UUCWComplex, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(UUCP))))
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TCFButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(TCFvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ECFvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SimpleUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UUCWSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AverageUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UUCWAverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComplexUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UUCWComplex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UUCW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SimpleActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UAWSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AverageActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UAWAverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComplexActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UAWComplex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(UAW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(UUCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(PF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(LOCperPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(LOCperUCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(UCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(LOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(PM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCFvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCFvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCFvalueActionPerformed

    private void TCFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCFButtonActionPerformed
        // TODO add your handling code here:
        new TCF().setVisible(true);
    }//GEN-LAST:event_TCFButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ECF().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        tcfvalue = Double.parseDouble(TCFvalue.getText());
        ecfvalue = Double.parseDouble(ECFvalue.getText());
        simpleUCvalue = 5 * Integer.parseInt(SimpleUC.getText());
        averageUCvalue =10 * Integer.parseInt(AverageUC.getText());
        complexUCvalue = 15 * Integer.parseInt(ComplexUC.getText());
        UUCWSimple.setText(Integer.toString(simpleUCvalue));
        UUCWAverage.setText(Integer.toString(averageUCvalue));
        UUCWComplex.setText(Integer.toString(complexUCvalue));
        UUCWvalue = simpleUCvalue+averageUCvalue+complexUCvalue;
        UUCW.setText(Integer.toString(UUCWvalue));
        simpleActorvalue = 1 * Integer.parseInt(SimpleActor.getText());
        averageActorvalue =2 * Integer.parseInt(AverageActor.getText());
        complexActorvalue = 3 * Integer.parseInt(ComplexActor.getText());
        UAWSimple.setText(Integer.toString(simpleActorvalue));
        UAWAverage.setText(Integer.toString(averageActorvalue));
        UAWComplex.setText(Integer.toString(complexActorvalue));
        UAWvalue = simpleActorvalue+averageActorvalue+complexActorvalue;
        UAW.setText(Integer.toString(UAWvalue));
        UUCPvalue = UUCWvalue + UAWvalue;
        UUCP.setText(Integer.toString(UUCPvalue));
        PFvalue =  Integer.parseInt(PF.getText());
        UCPvalue = tcfvalue * ecfvalue * UUCPvalue * PFvalue;
        double UCPRounded = Math.round(UCPvalue * 100D) / 100D;
        UCP.setText(Double.toString(UCPRounded));
        int index = metricsuite.jTabbedPane1.getSelectedIndex();
//        saveCurrentUCP(metricsuite.jTabbedPane1.getTitleAt(index));
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LOCperUCPvalue = Integer.parseInt(LOCperUCP.getText());
        LOCperPMvalue = Integer.parseInt(LOCperPM.getText());
        int ucpvalue = (int)UCPvalue;
        int loc = ucpvalue * LOCperUCPvalue;
        int pm =(int) loc / LOCperPMvalue;
        int hoursvalue = (int) pm *160;
        
        hours.setText(Integer.toString(hoursvalue));
        int index = metricsuite.jTabbedPane1.getSelectedIndex();
//        saveCurrentUCP(metricsuite.jTabbedPane1.getTitleAt(index));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LOCperUCPvalue = Integer.parseInt(LOCperUCP.getText());
        int ucpvalue = (int)UCPvalue;
        int loc = ucpvalue * LOCperUCPvalue;
        LOC.setText(Integer.toString(loc));
        int index = metricsuite.jTabbedPane1.getSelectedIndex();
//        saveCurrentUCP(metricsuite.jTabbedPane1.getTitleAt(index));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LOCperUCPvalue = Integer.parseInt(LOCperUCP.getText());
        LOCperPMvalue = Integer.parseInt(LOCperPM.getText());
        int ucpvalue = (int)UCPvalue;
        int loc = ucpvalue * LOCperUCPvalue;
        int pm =(int) loc / LOCperPMvalue;
        PM.setText(Integer.toString(pm));
        int index = metricsuite.jTabbedPane1.getSelectedIndex();
//        saveCurrentUCP(metricsuite.jTabbedPane1.getTitleAt(index));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField AverageActor;
    public static javax.swing.JTextField AverageUC;
    public static javax.swing.JTextField ComplexActor;
    public static javax.swing.JTextField ComplexUC;
    public static javax.swing.JTextField ECFvalue;
    public static javax.swing.JTextField LOC;
    public static javax.swing.JTextField LOCperPM;
    public static javax.swing.JTextField LOCperUCP;
    public static javax.swing.JTextField PF;
    public static javax.swing.JTextField PM;
    public static javax.swing.JTextField SimpleActor;
    public static javax.swing.JTextField SimpleUC;
    private javax.swing.JButton TCFButton;
    public static javax.swing.JTextField TCFvalue;
    public static javax.swing.JTextField UAW;
    public static javax.swing.JTextField UAWAverage;
    public static javax.swing.JTextField UAWComplex;
    public static javax.swing.JTextField UAWSimple;
    public static javax.swing.JTextField UCP;
    public static javax.swing.JTextField UUCP;
    public static javax.swing.JTextField UUCW;
    public static javax.swing.JTextField UUCWAverage;
    public static javax.swing.JTextField UUCWComplex;
    public static javax.swing.JTextField UUCWSimple;
    public static javax.swing.JTextField hours;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
